
title: Femifesto
description: 
baseurl: "/femifesto" # the subpath of your site, e.g. /blog
url: "http://hdlab.space/" # the base hostname & protocol for your site
github_repo: Femifesto # the GitHub repo name for your project
github_username: femifesto

social_link: gmail
social_username: femifesto2020

theme_color: light

# Build settings
markdown: kramdown

collections:
    cantigas:
      output: true
    preguntas_respuestas:
      output: true